### ISSUE TITLE
Problems opening the property. owl in Protege

### ISSUE THREAD

**Issue by mabablue** [stuchalk/scidata#13]
org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=8:column=17] Expecting rdf:RDF element.

**Comment by stuchalk** [comment]
I have cleaned up the file and verified that it is in conformance with the schema.  Should work now but let me know...

**Comment by mabablue** [comment]
Still Problems
[cid:image003.png@01D5D134.B36E6A00]

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Stuart Chalk<mailto:notifications@github.com>
Gesendet: Mittwoch, 22. Januar 2020 14:54
An: stuchalk/scidata<mailto:scidata@noreply.github.com>
Cc: Magagna Barbara<mailto:Barbara.Magagna@umweltbundesamt.at>; Author<mailto:author@noreply.github.com>
Betreff: Re: [stuchalk/scidata] Problems opening the property. owl in Protege (#13)


I have cleaned up the file and verified that it is in conformance with the schema. Should work now but let me know...

-

**Comment by stuchalk** [comment]
Is it the same issue? (I see there is an image embedded after "Still Problems' but it is not displaying)  Could you restart Protege are make sure the file is reload?  It could be that the file is cached by Protege.   Also, what ontology are you loading we you see this issue? (I can try and reproduce the problem if I know that)

**Comment by mabablue** [comment]
Will do thanks

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Stuart Chalk<mailto:notifications@github.com>
Gesendet: Mittwoch, 22. Januar 2020 15:04
An: stuchalk/scidata<mailto:scidata@noreply.github.com>
Cc: Magagna Barbara<mailto:Barbara.Magagna@umweltbundesamt.at>; Author<mailto:author@noreply.github.com>
Betreff: Re: [stuchalk/scidata] Problems opening the property. owl in Protege (#13)


Is it the same issue? (I see there is an image embedded after "Still Problems' but it is not displaying) Could you restart Protege are make sure the file is reload? It could be that the file is cached by Protege. Also, what ontology are you loading we you see this issue? (I can try and reproduce the problem if I know that)

-

**Comment by mabablue** [comment]
sorry not solved. May be I do something wrong...  but if you could help I would be thankful... [error message](https://github.com/Umweltbundesamt/test/blob/master/property_owl_issue.PNG)

**Comment by stuchalk** [comment]
The image that you linked to is not available for me to look at.  If you would like you can send it to my email at schalk@unf.edu.  I would like to figure this out as I it needs to work!
